version: '3.2'
services:
  db:
    image: postgres:10.18-bullseye
    environment:
      - POSTGRES_DB=hitech_apd
      - POSTGRES_PASSWORD=cms
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    expose:
      - 5432
    ports:
      - 54325:5432

  mongo:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_INITDB_DATABASE=admin
      - MONGO_DATABASE_USERNAME=mongo
      - MONGO_DATABASE_PASSWORD=cms
      - MONGO_DATABASE=eapd
    volumes:
      - mongodata:/mongodata
      - ./api/db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command: [--auth]
    expose:
      - 27017
    ports:
      - 27017:27017

  web:
    build: ./web
    image: cms-eapd/web
    environment:
      - API_URL=http://localhost:8081
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
    volumes:
      - type: bind
        source: ./web
        target: /app
        consistency: delegated
      - /app/node_modules
      - ./schemas:/app/src/static/schemas
    ports:
      - 8080:8001

  api:
    build: ./api
    image: cms-eapd/api
    depends_on:
      - db
      - mongo
    environment:
      - PORT=8000
      - DEV_DB_NAME=${DEV_DB_NAME:-hitech_apd}
      - TEST_DB_NAME=${TEST_DB_NAME:-hitech_apd_test}
      - NODE_ENV=development
      - DISABLE_SAME_SITE=yes
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_API_KEY=${OKTA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_ADMIN_URL=${MONGO_ADMIN_URL:-mongodb://admin-user:admin-password@mongo:27017/admin}
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:cms@mongo:27017/eapd?authSource=admin}
      - MONGO_DATABASE=${MONGO_DATABASE:-eapd}
    volumes:
      - type: bind
        source: ./api
        target: /app
        consistency: delegated
      - /app/node_modules
    ports:
      - 8081:8000
      - 9229:9229

volumes:
  pgdata:
  mongodata:
