name: Deploy Storybook
on:
  pull_request:
    branches:
      - main
    paths:
      [
        'web/.storybook/**',
        'web/src/stories/**',
        'web/src/**/*.story.js',
        'web/src/**/*.story.mdx',
        'web/src/components/**',
        'web/src/containers/**'
      ]
jobs:
  storybook-deploy:
    runs-on: ubuntu-18.04
    environment: Preview
    timeout-minutes: 60
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          cd web
          yarn install
          yarn build:storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs-build # The folder that the build:storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
